### ISSUE TITLE
procedures are no longer valid

### ISSUE THREAD

**Issue by cordoval** [cordoval/Symfony2Colors#7]
cc @mbadolato have you tried recently this on mac with the latest version?

i am running into a problem even though i created /Users/lindacarhuas/Library/Preferences/WebIde90/codestyles and put there Symfony2.xml

but i think is not the codestyle but everything

I rememeber I made it work on my other computers somehow but can't recall perhaps we should update the instructions

cc @sstok

**Comment by mbadolato** [comment]
Yeah the PHPSTorm preference files are different now, but I don't recall where they're located offhand. When I have some time I'll try to dig for them. I've been upgrading my storm license and the file was converted/imported when new versions were installed so I haven't had to manually follow our instructions for a long time

**Comment by cordoval** [comment]
perhaps export and push them to this repo would be a nice to have :blue_book:

**Comment by dhanielo** [comment]
Solution: [Clone this repo] Copy Symfony2.xml to Symfony2.icls and remove <?xml version="1.0" encoding="UTF-8"?>. Create directory  ~/.WebIde90/config/colors and move new file to folder. Restart PHPStorm, choose new theme and restart again!

**Comment by mbadolato** [comment]
I've added my version of the Symfony2.icls file. It may differ slightly from the XML file as I may have tweaked settings here and there. It's there as a reference at the very least

**Comment by cordoval** [comment]
thanks @mbadolato
